### ISSUE TITLE
After installing extensions: "Error loading custom command cci.cmd_upgrade_qt_recipe" in each conan call

### ISSUE THREAD

**Issue by hdnn** [conan-io/conan-extensions#104]
Hi! I work with conan installed by standalone installer(not by pip).  After installing latest conan-extensions every conan command call starts with the error:
```
ERROR: Error loading custom command cci.cmd_upgrade_qt_recipe: No module named 'xml.etree'
```
Example: 
![image](https://github.com/conan-io/conan-extensions/assets/8512124/8d56538d-d03a-4a27-8024-d6562a09dcea)
Steps to reproduce:
1) Download and install https://github.com/conan-io/conan/releases/download/2.0.14/conan-win-64.exe
2) Run: conan config install https://github.com/conan-io/conan-extensions.git
3) Run any other conan command(`conan --version`)

**Comment by memsharded** [comment]
Hi @hdnn 

Thanks for your report.
I think this is kind of expected, the extensions are Python code and can have any arbitrary Python library, including external pip-packages, while the self-contained executable is limited to the core needed libraries, and can't be extended with extra pip packages.

We need to talk about this, but it might be possible that the recommendation would be to use the ``pip`` installed Conan to be able to enable certain extensions. Also, it is likely that you don't need this extension at all, then you can just remove it from your cache. In production, the recommendation would be to put the extensions you need and want in your own repo and ``conan config install`` your repo, and not the ``conan-extensions`` one.

**Comment by hdnn** [comment]
Yeah, the issue with `extensions\commands\cci\cmd_upgrade_qt_recipe.py` file which is definitely not required for me, so I'll just delete it

**Comment by ericLemanissier** [comment]
@memsharded I guess it'd be nicer to users if the this xml.etree module was not used.  I can see that [conan uses xml.dom.minidom](https://github.com/search?q=repo%3Aconan-io%2Fconan+xml.dom&type=code), so I'll migrate cmd_upgrade_qt_recipe to minidom.
Where are the available modules documented ?

**Comment by memsharded** [comment]
> Where are the available modules documented ?

I am afraid they aren't, this is automatically collected by ``pyinstaller`` when it creates the self-contained bundle.
