### ISSUE TITLE
[Question] Unable to upload build info

### ISSUE THREAD

**Issue by hdnn** [conan-io/conan-extensions#105]
Hi!
I'm doing migration to conan 2.0 from conan 1.x.x and `conan_build_info --v2` which works fine on prod Artifactory. But the new `conan art:build-info upload` command returns 
```
ERROR: 403: Request for 'conan:my_company/bzip2/1.0.8/stable/d290a2bca88be37304ea12f0db2a6149/export/conanfile.py' is forbidden for user: 'gitlab', You must have annotate permission on this path
```
which means I need to extend permissions for `gitlab` user. Can anyone explain why? What the difference in this two approaches? I ask because I need to justify to the security team why this is necessary.

I've tried to check the difference on created by my own trial Artifactory account.
According to the [How to manage Build Info's in Artifactory](https://github.com/conan-io/conan-extensions/tree/51933583b210ed8d2137276d081252a2b801f3b4/extensions/commands/art#how-to-manage-build-infos-in-artifactory) I repeated all steps:
```
conan create . --name bzip2 --version=1.0.8 --user=user --channel=testing -r test-conan -f json > out.json
conan upload bzip2/1.0.8@user/testing -r test-conan -c
conan art:build-info create out.json $(BUILD_NAME) $(BUILD_ID) test-conan --url=https://conan2bi.jfrog.io/artifactory --user=$(ADMIN_NAME) --password=$(ADMIN_PASS) --with-dependencies > bi.json
conan art:build-info upload bi.json --url=https://conan2bi.jfrog.io/artifactory --user=$(ADMIN_NAME) --password=$(ADMIN_PASS)
```
First 3 commands work without issue and produce correct json files.
But the last command output:
```
ERROR: 400: Failed to set properties on test-conan:user/bzip2/1.0.8/testing/89da1be3ae77a6034b86f0298f4f2b33/export/conanfile.py
```
What can be wrong there?

**Comment by memsharded** [comment]
Hi @hdnn 

I think that the Artifactory BuildInfo always needed to set properties on artifacts to set the BuildName and BuildID property on every uploaded artifact. 
The issue is that in Conan 1.X the set of properties was integrated with the ``conan upload`` command, in a quite ugly and coupled way. The user doing ``conan upload`` had to had annotate permissions. Were you using different users for ``conan upload`` and for the buildInfo upload?

Now in Conan 2.0 the flow is completely decoupled, ``conan create & upload`` does nothing related to buildInfo, but it is the ``conan art:build-info`` commands the one setting properties when they upload the buildInfo.

**Comment by hdnn** [comment]
@memsharded I figured out what was wrong. From my perspective current documentation of `conan art:build-info create` is not clearly explain `repository` field:

> repository           Repository to look artifacts for.

I understood it like a name of repository from `conan remote list` which I use in `conan upload`. But I was wrong.
I have **conan**, **conan-local** and **conan-remote** repositories by default. 
![image](https://github.com/conan-io/conan-extensions/assets/8512124/1b26dbfc-09e4-43f6-9317-62cf3e227f34)
Every time when I need to configure conan client, I pick **conan** then click on **Set Me Up** button and use url to conan to upload my package. But for `conan art:build-info create` I must use **conan-local**, otherwise I'll get 403 or 400 error as described above.
So, I think it would be nice to add some explanation to docs, that `conan art:build-info create` expects a name of local repository(`conan-local`), not to general one(`conan`)

**Comment by czoido** [comment]
Hi @hdnn,

Thanks a lot por reporting this. We will check the documentation and help of the commands to make that more clear.
