### ISSUE TITLE
[bug] conan art:server add results in ERROR: 400: Couldn't perform replication, check server logs for more information.

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan-extensions#128]
Hello,

I am using conan 2.3.0. I only checked on a linux machine, running python 3.9.18.

Running `conan art:server add my_artifactory --user 'admin' --password 'password' 'http://artifactory:8082/artifactory/api/conan/conan-dev-local' -vvv`

Gives me:
```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/conan/cli/cli.py", line 193, in run
    command.run(self._conan_api, args[0][1:])
  File "/usr/local/lib/python3.9/site-packages/conan/cli/command.py", line 180, in run
    sub.run(conan_api, parser, *args)
  File "/usr/local/lib/python3.9/site-packages/conan/cli/command.py", line 197, in run
    info = self._method(conan_api, parent_parser, self._parser, *args)
  File "/home/carl//.conan2/extensions/commands/art/cmd_server.py", line 123, in server_add
    token = api_request("get", f"{url}/api/security/encryptedPassword", user, password)
  File "/home/carl//.conan2/extensions/commands/art/utils.py", line 80, in api_request
    raise BadRequestException(response_to_str(response))
utils.BadRequestException: 400: Couldn't perform replication, check server logs for more information.

ERROR: 400: Couldn't perform replication, check server logs for more information.
```

I first thought the error was caused because the targetted server was a virtual one, but changing it a local one ended up in the same result. I did not (know how to?) find anything interesting in the server's log either.

Could you please have a look?

Thanks in advance.

**Comment by Todiq** [comment]
Thanks for the quick answer!

I am using version 7.77.11. Moving the positional arguments first did not improve anything.

**Comment by czoido** [comment]
@Todiq 

Is it the cpp version by any chance? This commands need access to the Artifactory API that's only available for Pro versions.

**Comment by czoido** [comment]
@Todiq I think the problem is that you are adding the repo name to the server, can you try to use `http://artifactory:8082/artifactory` as argument instead?

**Comment by Todiq** [comment]
That fixed it. The error message was not very clear.

Thank you very much!
