### ISSUE TITLE
[question] How to upload & promote a package that was exported to the local cache

### ISSUE THREAD

**Issue by Todiq** [conan-io/conan-extensions#129]
Hello,

I am trying to follow artifactory best practices by having 3 different conan repos: one for dev, one for tests and one for prod.

If I understood correctly, having a pro license, I can promote a build from one repo to the other.

However, after `conan build` and `conan export-pkg` have been run, there is no direct and easy way to upload a package to a repo, so that it can later be promoted with the JFROG CLI (unless uploaded with the dedicated CLI command, rather than `conan upload`).

Now, the `conan art:promote` was made for that purpose, but I don't really understand how it works.

I tried creating a graph when running `conan build` and passing it to `conan art:build-info`. That gives a very small file, while I expected it to list all my dependencies (there are properly listed inside `graph.json`), but none of that is present. Could you please give me a hint of how all of that works? I found no proper documentation regarding a full flow with these commands (from a `conan build` to an upload & promotion). Needless to say that JFROG CLI equivalents are not very clear either.

Thanks in advance!

**Comment by memsharded** [comment]
Hi @Todiq 

Thanks for your question.

When a command that ``conan install/build/create/export-pkg`` runs, it can create with ``--format=json`` a serialized graph file with the dependency graph, including if every node in the graph was built, downloaded, or already in cache.

The ``conan build`` generates the dependency graph in Conan 2, but not in Conan 1. Still, the current build will not be part of the graph, because it is not a package. You might want to capture the graph in the ``conan export-pkg`` instead.

Once you have the graph, you pass that graph to the ``conan list --graph=mygraph.json`` command. This command will generate a "package list" with some logic, depending on the arguments. It can list only the packages that were built from source, or all the dependencies. Make sure to check this file that it should contain both the recipes and binaries that you want to upload.

Once you have the package list, it should be possible to pass it to ``conan upload`` and then to the ``conan art:promote`` command.

This doesn't include the promotion, but it will include the create + upload: https://docs.conan.io/2/examples/commands/pkglists.html#building-and-uploading-packages, have you checked this one already? I think it might help.

**Comment by Todiq** [comment]
Hello @memsharded,

Thanks for the answer.

I authenticated successfully with `conan art:server add ...` , but am unable to make `conan art:promote` work properly. Here is the output:

```bash
➜  ~ conan art:promote list.json --from="dev" --to="staging" --url 'http://artifactory:8082/artifactory'
ERROR: Package list must come from the remote associated with dev, but found from local cache
```

I tried to pass `--remote` and `--server` as well, but it would not work either. Would you mind helping me out? Thanks in advance.

**Comment by memsharded** [comment]
The promotion can only happen from server repo to repo, and that means that the "package list" that you are passing must have the recipes and packages that you want to promote in the right ``from`` repo in the ``list.json`` file.

To achieve that, it is necessary to create the right ``list.json`` file. Probably, what you want is to capture the result of the upload like:
```
conan upload --list=mycachelist.json -r=myremote -c --format=json > myremotelist.json
conan art:promote myremotelist.json --from=myremote ...
```
Please let me know if this makes sense.

**Comment by Todiq** [comment]
It does!

I managed to build & upload my project and its dependencies, but could only promote my package. It fails when trying to promote boost. Did I do something wrong?

```bash
conan art:promote linux-x86-64-release-list.json --from="conan-dev-local" --to="conan-staging-local" --server="myserver"
-------- Promoting _/pkg/1.1/_/fa5eb9b932b755e3ea620259a32235f8/export/ --------
Promoted file
-------- Promoting _/pkg/1.1/_/fa5eb9b932b755e3ea620259a32235f8/package/6c8ec0f43af259bcc11e37ad3dfbda909dc270ce/f1e0f2fd8cde87116256e0d0ac65fd55 --------
Promoted file
-------- Promoting _/boost/1.81.0/_/5253fbf3f16ff1dc0f0991c92632[51](https://gitlab.mycompany.com/Project/pkg/-/jobs/3784#L51)ac/export/ --------
ERROR: Error requesting api/copy/conan-dev-local/_/boost/1.81.0/_/[52](https://gitlab.mycompany.com/Project/pkg/-/jobs/3784#L52)53fbf3f16ff1dc0f0991c9263251ac/export/?to=/conan-staging-local/_/boost/1.81.0/_/5253fbf3f16ff1dc0f0991c9263251ac/export/&suppressLayouts=0: {
  "messages" : [ {
    "level" : "ERROR",
    "message" : "Failed to copy from src=conan-dev-local/_/boost/1.81.0/_/52[53](https://gitlab.mycompany.com/Project/pkg/-/jobs/3784#L53)fbf3f16ff1dc0f0991c9263251ac/export/ to target=/conan-staging-local/_/boost/1.81.0/_/5253fbf3f16ff1dc0f0991c9263251ac/export/: Could not find item at conan-dev-local:_/boost/1.81.0/_/5253fbf3f16ff1dc0f0991c9263251ac/export"
  } ]
}
```

**Comment by memsharded** [comment]
I am really confused about the error:
```
src=conan-dev-local/_/boost/1.81.0/_/52[53](https://gitlab.mycompany.com/Project/pkg/-/jobs/3784#L53)fbf3f16ff1dc0f0991c9263251ac/export/
```
It seems there is an URL of Gitlab interleaved? Do you know what does it mean?

The code that compose the path is relatively simple:
```python
def _get_export_path_from_rrev(rrev):
    recipe_ref = RecipeReference.loads(rrev)
    user = recipe_ref.user or "_"
    channel = recipe_ref.channel or "_"
    path = f"{user}/{recipe_ref.name}/{recipe_ref.version}/{channel}"
    if recipe_ref.revision:
        path += f"/{recipe_ref.revision}/export/"
    return path
```
It could be some CI logs replacement? The error message at the end seems correct: ``_/boost/1.81.0/_/5253fbf3f16ff1dc0f0991c9263251ac/export``. 

Can you also please verify that such a recipe revision exist in your "from" remote and that the contents of the ``export`` folder are the expected ones?

**Comment by Todiq** [comment]
I started from scratch today and did not encounter the issue anymore. I don't know what happened. Maybe a VPN disconnection or something.

However, although `conan upload ...` returned:
```bash
boost/1.81.0: Checking which revisions exist in the remote server
boost/1.81.0: Recipe 'boost/1.81.0#5253fbf3f16ff1dc0f0991c9263251ac' already in server, skipping upload
boost/1.81.0: Package 'boost/1.81.0#5253fbf3f16ff1dc0f0991c9263251ac:3fb36d50f33cf617ab5a778cd0f6b3a0f63a1ccd#8bad55d6c2c4593707273a5c55e6976d' already in server, skipping upload
```

I still got:
```bash
-------- Promoting _/boost/1.81.0/_/5253fbf3f16ff1dc0f0991c9263251ac/export/ --------
ERROR: Error requesting api/copy/conan-dev-local/_/boost/1.81.0/_/5253fbf3f16ff1dc0f0991c9263251ac/export/?to=/conan-staging-local/_/boost/1.81.0/_/5253fbf3f16ff1dc0f0991c9263251ac/export/&suppressLayouts=0: {
  "messages" : [ {
    "level" : "ERROR",
    "message" : "Failed to copy from src=conan-dev-local/_/boost/1.81.0/_/5253fbf3f16ff1dc0f0991c9263251ac/export/ to target=/conan-staging-local/_/boost/1.81.0/_/5253fbf3f16ff1dc0f0991c9263251ac/export/: Could not find item at conan-dev-local:_/boost/1.81.0/_/5253fbf3f16ff1dc0f0991c9263251ac/export"
  } ]
}
```

I had to `conan upload ... --force`, to make it finally work. Maybe an extra check could be done in the `conan art:promote` command?

**Comment by memsharded** [comment]
Uhm, it sounds that maybe ``conan-dev-local/_/boost/1.81.0`` was corrupted on the server or something like that, ``conan upload`` thought that the package was there, but some file could be missing, so the promotion failed. ``--force`` can indeed fix these corruptions. I guess it will not be possible to reproduce anymore now, is it?

**Comment by Todiq** [comment]
Hello,

Indeed it would be quite hard. It never happened again ever since.

If it ever does, I will open back the ticket. Thank you for your help!
