### ISSUE TITLE
art:build-info create skips packages with binary: "Download"

### ISSUE THREAD

**Issue by cregecambrin** [conan-io/conan-extensions#140]
I am trying to use `art:build create` as part of a github action.
The job being run on a clean node every time, when i run `conan install`, a lot of packages end up having `binary: "Download"` in the generated intermediate .json file.

Then, when I run `art:build-info create` on that file, because of [this line](https://github.com/conan-io/conan-extensions/blob/d42104959812a405471c3054909d5d9e754de927/extensions/commands/art/cmd_build_info.py#L248), those packages are not included in the output.

Is that intentional?
I was able to workaround this by running  `conan install`  twice, which caused the second run to have  `binary: "Cache"`, and then using the `--add-cached-deps` option for `art:build-info create` . However, I believe there should be an option for including downloaded packages, like there's one for cached ones.

**Comment by memsharded** [comment]
Hi @cregecambrin 

Thanks for your report.

I am not an expert in this extension, but it indeed seems expected that ``--add-cached-deps`` is taking into account both packages that were previously in the cache and those that was just downloaded into the cache. 
But I'll ping @czoido and @danimtb to double check.

**Comment by danimtb** [comment]
Indeed as @memsharded pointed out, in the same fashion, we already added that `--add-cached-deps` to take those into account for creating the build info. We could do the same for the downloaded ones as @cregecambrin requests.

@czoido maybe at this point we could reconsider if we should include all dependencies or just go on with adding another command line flag to keep supporting different sources for dependencies (and not only the "built" ones as we originally envisioned)

**Comment by czoido** [comment]
> Indeed as @memsharded pointed out, in the same fashion, we already added that `--add-cached-deps` to take those into account for creating the build info. We could do the same for the downloaded ones as @cregecambrin requests.
> 
> @czoido maybe at this point we could reconsider if we should include all dependencies or just go on with adding another command line flag to keep supporting different sources for dependencies (and not only the "built" ones as we originally envisioned)

I think it's fine to include the Download nodes when using `--add-cached-deps`. I'll open a PR to fix this, thanks a lot @cregecambrin for reporting.

**Comment by czoido** [comment]
Hi @cregecambrin,

After https://github.com/conan-io/conan-extensions/pull/141 was merged, it should work now, can you please check?

Thanks a lot!

**Comment by cregecambrin** [comment]
> Hi @cregecambrin,
> 
> After #141 was merged, it should work now, can you please check?

Hi @czoido,
I can confirm the issue is solved. Thank you!
