### ISSUE TITLE
[feature] Publish buildinfo in a project specific artifactory repo

### ISSUE THREAD

**Issue by fg68** [conan-io/conan-extensions#145]
Provide an option to the conan_build_info --v2 publish subcommand to be able to specify an artifactory project with a dedicated buildinfo repository where the buildinfo should be stored.

Currently one can only perform this with the jfrog CLI build upload command (see https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-BuildUpload) but this requires an additional tool in the CI pipeline (including setup and authentication) though the principal functionality is already contained in the conan_build_info tool (see also https://github.com/czoido/conan-build-info-example/issues/1).

- [*] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment]
this ticket has been moved to the ``conan-extensions`` repository, where the new ``conan art:commands`` extension commands for Artifactory, including commands to generate the BuildInfo are.

@czoido any update regarding this ticket?

**Comment by czoido** [comment]
Closing this as solved by https://github.com/conan-io/conan-extensions/pull/56 that introduced support for projects in build info. Thanks @fg68 for reporting.
