### ISSUE TITLE
Error when installing conan-extensions

### ISSUE THREAD

**Issue by MartinDelille** [conan-io/conan-extensions#48]
I had the following error when trying to install conan-extensions:

```
$ conan config install https://github.com/conan-io/conan-extensions.git
ERROR: Error loading custom command qt.cmd_upgrade_qt_recipe: No module named 'ruamel'
Trying to clone repo: https://github.com/conan-io/conan-extensions.git
Repo cloned!
Copying file cmd_property.py to /Users/martindelille/.conan2/extensions/commands/art
Copying file cmd_server.py to /Users/martindelille/.conan2/extensions/commands/art
Copying file cmd_build_info.py to /Users/martindelille/.conan2/extensions/commands/art
Copying file cmd_bump_deps.py to /Users/martindelille/.conan2/extensions/commands/recipe
Copying file cmd_convert_txt.py to /Users/martindelille/.conan2/extensions/commands/migrate
Copying file cmd_export_all_versions.py to /Users/martindelille/.conan2/extensions/commands/cci
Copying file cmd_upgrade_qt_recipe.py to /Users/martindelille/.conan2/extensions/commands/cci
Copying file cmd_list_v2_ready.py to /Users/martindelille/.conan2/extensions/commands/cci
```

I installed the missing package using `pip install ruamel.yaml`.

**Comment by memsharded** [comment]
Thanks for reporting.

This is weird. It didn't fail on my side, and I don't have that ruamel.yaml package installed at all (Windows).
I haven't found references to it in the repo either, but also I cannot see the "qt" layer either.

**Comment by ericLemanissier** [comment]
this `qt.cmd_upgrade_qt_recipe` looks like a remnant of a development version of the extension. The final version is named cci.cmd_upgrade_qt_recipe and does not use `ruamel`
You can simply remove it with `rm ~/.conan2/extensions/commands/qt/cmd_upgrade_qt_recipe.py`

**Comment by RubenRBS** [comment]
That seems to be it! @MartinDelille tested your original PR so it's feasible and old version stuck around. Note that `conan config install`s are additive, they don't remove anything that's already there from another install, which is fine when things are "done", but a bit riskier when testing & developing

**Comment by MartinDelille** [comment]
Indeed!
