### ISSUE TITLE
Certificate verification is failing when using conan art:server add

### ISSUE THREAD

**Issue by psamadda** [conan-io/conan-extensions#70]
I have installed the conan extensions and tried to use the following command to add the JFROG server.
conan art:server add artifactory <server_name> --user=<user_name> --password=<password>
It generates an error: SSL: CERTIFICATE_VERIFY_FAILED
I tried to resolve it in two ways.
1. I tried to pass ssl-verify False for the above command. But could not make it.Can you mention the proper command with ssl-verification false.
2. I fetched the base64 encoded ASCII single certificate for the jfrog server and added the content in cacert.pem file. Then used the following command to install the cacert. But the issue persists. Can you guide me?
conan config install cacert.pem

**Comment by memsharded** [comment]
Hi @psamadda 

Thanks for your report.
It would be good to know the client machine configuration, OS, platform, etc., and also getting a more complete error message.

Also, it would be very convenient to know if this happens also in other different machines with other configurations/OS, or only that one.

**Comment by psamadda** [comment]
OS - redhat 8.2,x86_64
I have attached the error log.
2. I tried to add conancenter like the following with no username and password. It says 404. Can you please suggest how I can add conancenter?
conan art:server add conancenter https://center.conan.io/
Exception: 404: Not Found


[error.txt](https://github.com/conan-io/conan-extensions/files/12665168/error.txt)

**Comment by memsharded** [comment]
I think there is some misunderstanding.
You cannot authenticate against ConanCenter. This is a special server we control, behind a CDN for scale, etc.
You need to authenticate to your own Artifactory server.

For using Conan client with the ConanCenter server, you don't need these extensions at all. I am not sure if I am missing something.

**Comment by psamadda** [comment]
Thank you for the information about conancenter. Is there any way to add my jfrog server with ssl_verify set to false?

**Comment by memsharded** [comment]
Sure, check ``conan remote add -h``:
```
 conan remote add -h
usage: conan remote add [-h] [-v [V]] [--insecure] [--index INDEX] [-f] name url

Add a remote.

positional arguments:
  name           Name of the remote to add
  url            Url of the remote

optional arguments:
  -h, --help     show this help message and exit
  -v [V]         Level of detail of the output. Valid options from less verbose to more verbose: -vquiet, -verror, -vwarning, -vnotice, -vstatus, -v or
                 -vverbose, -vv or -vdebug, -vvv or -vtrace
  --insecure     Allow insecure server connections when using SSL
  --index INDEX  Insert the remote at a specific position in the remote list
  -f, --force    Force the definition of the remote even if duplicated
````
So passing the ``--insecure`` arg allows to define your own remote without a secure connection
```
conan remote add myremote <myurl> --insecure
```
Recall that your ``<myurl>`` is the one given by ``Set me up`` in Artifactory, not the WebUI url

**Comment by psamadda** [comment]
1.  Using "conan remote add artifactory <myurl> --insecure", I can add artifactory server, but when I am trying to add build -info, I am getting the following error. My requirement is to run 'conan art:server add artifactory ...' using either cacert.pem or --insecure. Is it possible?

The command: 
conan art:build-info create create_debug.json hello_debug 1 https://myartifactory.com:443/artifactory/ConanPackages/_/hello/1.0 --server artifactory --with-dependencies > hello_debug.json

ERROR: The server specified (artifactory) is not configured. Use `conan art:server add artifactory` to configure it.

**Comment by czoido** [comment]
Hi @psamadda,

Thanks for reporting, I think what's happening in the creation of the BuildInfo is that the arguments are not correct. Please, check the arguments help for art:build-info:

```
conan art:build-info create --help
usage: conan build-info create [-h] [-v [V]] [--server SERVER] [--url URL] [--user USER] [--password PASSWORD] [--with-dependencies]
                               json build_name build_number repository

Creates BuildInfo from a Conan graph json from a conan install or create.

positional arguments:
  json                 Conan generated JSON output file.
  build_name           Build name property for BuildInfo.
  build_number         Build number property for BuildInfo.
  repository           Repository to look artifacts for.

optional arguments:
  -h, --help           show this help message and exit
  -v [V]               Level of detail of the output. Valid options from less verbose to more verbose: -vquiet, -verror, -vwarning, -vnotice,
                       -vstatus, -v or -vverbose, -vv or -vdebug, -vvv or -vtrace
  --server SERVER      Server name of the Artifactory to get the build info from.
  --url URL            Artifactory url, like: https://<address>/artifactory. This may be not necessary if all the information for the Conan
                       artifacts is present in the local cache.
  --user USER          User name for the repository.
  --password PASSWORD  Password for the user name.
  --with-dependencies  Whether to add dependencies information or not. Default: false.
```

The 4th argument is `repository` that is the name of the repository in Artifactory, not the full url, so in this case it should be `ConanPackages`. Could you try with these arguments?

```
conan art:build-info create create_debug.json hello_debug 1 ConanPackages --server artifactory --with-dependencies > hello_debug.json
```

Thanks a lot, hope this helps

**Comment by psamadda** [comment]
Thanks for pointing out that. I am still getting the error "The server specified (artifactory) is not configured. Use conan art:server add artifactory to configure it". I am failing to add the remote using "conan art:server add artifactory".
conan art:server add artifactory https://vmname/artifactory --user=<username>--password=<Password>.
I tried to use cacert.pem but it did not work. I have attached the error log.


[error.txt](https://github.com/conan-io/conan-extensions/files/12712335/error.txt).

**Comment by czoido** [comment]
Hi @psamadda,

Are you still having problems with this? Could you test setting the `REQUESTS_CA_BUNDLE` environment variable?

Thanks!

**Comment by psamadda** [comment]
Sorry for the late reply. The environment variable resolves the issue. Thanks for your reply.

**Comment by czoido** [comment]
I'm glad to hear that @psamadda, I'm closing this issue now as this is not related with the extension itself but with the requests configuration. Feel free to reopen if you have any more questions. Thanks!
