### ISSUE TITLE
SBOM XML namespace cannot be parsed by dependencytrack

### ISSUE THREAD

**Issue by hedtke** [conan-io/conan-extensions#88]
Uploading an SBOM in XML 1.4 format results in parsing errors in dependencytrack. The namespace ns0 cannot be parsed properly.

The image shows two SBOMs in XML format. The one created by this extension uses `xmlns:ns0` and the parser crashes:
```
2023-11-06 07:46:03,118 WARN [BomUploadProcessingTask] The BOM uploaded is not in a supported format. Supported formats include CycloneDX XML and JSON
```
The other example created with another tool does not use the namespace and dependencytrack works fine
![Bild](https://github.com/conan-io/conan-extensions/assets/726611/dd6b26e6-7578-41fb-9be2-33311d873a36)

Can we deactivate the ns0?

**Comment by memsharded** [comment]
We might need the inputs from @jkowalleck
 and @andreas-hilti here?

**Comment by memsharded** [comment]
Thanks @jkowalleck 

Lets remove them then! Do you plan to do the PR yourself @hedtke ?

**Comment by jkowalleck** [comment]
Anyway

> The namespace ns0 cannot be parsed properly.

I doubt that this is true. and if so, then @DependencyTrack is bugged.
FYI: @nscuro @msymons

**Comment by hedtke** [comment]
This is the problematic file. It is our guess that the namespace is the issue. When I switch from XML to JSON, dependency track works fine. Maybe the problem is somewhere else? 
[bom.xml.zip](https://github.com/conan-io/conan-extensions/files/13277347/bom.xml.zip)

**Comment by jkowalleck** [comment]
the XML is invalid to the schema. this is due to a bug in `cyclonedx-python-lib>=4,<5` (v4.*)
you should depend on `cyclonedx-python-lib>=3.1.5,!=4.*,<6`

details: 
* fix: https://github.com/CycloneDX/cyclonedx-python-lib/releases/tag/v5.0.0
* issue: Serialization of multy-licenses (https://github.com/CycloneDX/cyclonedx-python-lib/issues/365 fixes via https://github.com/CycloneDX/cyclonedx-python-lib/pull/466)

**Comment by hedtke** [comment]
The extension needs to be changed, because it is not compatible with v5. I could look into that within the next days. Just installing v5 instead of v4 does not work: `LicenseChoice` does not exist anymore

**Comment by jkowalleck** [comment]
i do not see why you would care for `LicenseChoice` at all.

here are some hints for migrating your code:
```py
def cyclonedx_major_version_is_5() -> bool:
  try:
     from cyclonedx import __version__
     return __version__ >= (5,)
  except ImportError:
    return False
```
 
more important is the API change related to the `LicenseFactory`
that is documented here https://github.com/CycloneDX/cyclonedx-python-lib/releases/tag/v5.0.0
and showcased here https://github.com/CycloneDX/cyclonedx-python-lib/blob/v5.0.0/examples/complex.py

**Comment by hedtke** [comment]
> Thanks @jkowalleck
> 
> Lets remove them then! Do you plan to do the PR yourself @hedtke ?

PR created: #89
