### ISSUE TITLE
Support for searching in multiple Artifactory repositories for the artifacts of dependencies

### ISSUE THREAD

**Issue by danieljuhasz93** [conan-io/conan-extensions#91]
The `conan art:build-info create` command currently only searches for artifacts in a single Artifactory repository. This can be specified by the `repository` positional argument. However, this is not sufficient as the dependencies of a package are frequently published to a different repository than the consumer package.

In our case some of the dependencies of the package we develop come from a different repository in Artifactory, hence the `conan art:build-info create` fails with the following message.

> There are no artifacts for the recipe. Probably the package was not uploaded before creating the Build Info. Please upload the package to the server and try again.

Would it be possible to update the handling of the `repository` argument to support searching in multiple Artifactory repositories preferably by providing the repositories as a list of comma-separated values?

**Comment by danimtb** [comment]
Hi @danieljuhasz93,

Thanks for your report. Indeed the feature you requested makes sense, but we have to check if that could make sense from the implementation point of view. Maybe multiple `repository` args can be used and the search order would be the same as provided in the command line.

I would give it a look in the code and let you know 😄

**Comment by danimtb** [comment]
Hi @danieljuhasz93,

I have opened a new PR implementing your feature request at https://github.com/conan-io/conan-extensions/pull/92. Could you give it a try and let me know if that would cover your use case?

Thank you!

**Comment by danimtb** [comment]
Closing as fixed by https://github.com/conan-io/conan-extensions/pull/95
