### ISSUE TITLE
[feature] Add token-based authentication to art:server command

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan-extensions#98]
In our company, we have an Artifactory server with SSO. Somehow, it is imcompatible with the way `art:server add` tries to get a token because the URL it tries to access doesn't exist. However, I can manually create an identity token and I'd like a way to specify it, e.g.:

    conan art:server add my_art https://artifactory.company.com --user=fschoenm --token=<token>

There may be some corner cases but essentially, the subcommand to add a server should just use the specified token instead of trying to generate it.

**Comment by danimtb** [comment]
Hi @fschoenm,

Thank you for the issue. I think it makes sense, easy to implement and will cover the SSO auth case, which probably is the most used one in Artifactory.

**Comment by danimtb** [comment]
Also, I believe that you can directly use the arguments ``--user <user> --password <token>`` in the build-info commands directly and it should work. However, I understand the need of such feature as using the ``--server`` is very convenient.

**Comment by fschoenm** [comment]
I see, thanks for the idea. I tried to follow the README as closely as possible, which is why I added a server first. I also made a quick-hack for accepting a token in my own art command extension, I just didn't feel comfortable sharing it but it seemed simple enough 😅
